package com.example.clifzyinfinite

object ClipzyCodeGenerator {

    fun generate(plan: AppPlan): String {

        return """
            // Generated by Clipzy Infinite

            App Name: ${plan.appName}

            Description:
            ${plan.description}

            Features:
            ${plan.features.joinToString("\n") { "- $it" }}

            Screens:
            ${plan.screens.joinToString("\n") { "- $it" }}

            Project Structure:

            app/
            ├── MainActivity.kt
            ├── screens/
            │   ├── HomeScreen.kt
            │   ├── MainFeatureScreen.kt
            │   ├── SettingsScreen.kt
            │   └── ProfileScreen.kt
            └── ClipzySmart.kt
        """.trimIndent()
    }
}